modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/team-abnormals/caverns_and_chasms/issues"
license = "https://github.com/team-abnormals/caverns_and_chasms/blob/main/LICENSE.txt"

[[mixins]]
    config = "caverns_and_chasms.mixins.json"

[[mods]]
    modId = "caverns_and_chasms"
    version = "${mod_version}"
    logoFile = "logo.png"
    enumExtensions = "META-INF/enum_extensions.json"
    itemIcon = "caverns_and_chasms:silver_ore"
    configBackground = "caverns_and_chasms:textures/block/cobblestone_tiles.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, five, Markus1002, hatsondogs, krypto"
    displayURL = "https://www.teamabnormals.com/mods/caverns-and-chasms"
    displayName = "Caverns & Chasms"
    description = '''
    Expands caves, mining, and more with tons of new content!
    '''

[[dependencies.caverns_and_chasms]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${mc_version}]"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.caverns_and_chasms]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neoforge},)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.caverns_and_chasms]]
    modId = "blueprint"
    type = "required"
    versionRange = "[${blueprint},)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.caverns_and_chasms]]
    # Ensure Architect's Palette loads after so we can fix its recipes.
    modId = "architects_palette"
    type = "optional"
    # it doesn't matter its version.
    versionRange = "(,)"
    ordering = "AFTER"
    side = "BOTH"
