package com.teamabnormals.caverns_and_chasms.core.other;

import com.teamabnormals.caverns_and_chasms.core.CCConfig;
import com.teamabnormals.caverns_and_chasms.core.CavernsAndChasms;
import com.teamabnormals.caverns_and_chasms.core.registry.CCItems;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.function.Supplier;

import static com.teamabnormals.caverns_and_chasms.core.registry.CCBlocks.*;
import static com.teamabnormals.caverns_and_chasms.core.registry.CCItems.*;


public class CCCreativeTabs {
	public static final DeferredRegister<CreativeModeTab> CREATIVE_TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, CavernsAndChasms.MOD_ID);

	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> CAVERNS_AND_CHASMS = CREATIVE_TABS.register(CavernsAndChasms.MOD_ID, () ->
			CreativeModeTab.builder()
					.title(Component.translatable("itemGroup.caverns_and_chasms.caverns_and_chasms"))
					.icon(() -> new ItemStack(CCItems.DEEPER_HEAD.get()))
					.displayItems(((parameters, output) -> {
						if (CCConfig.COMMON.creativeTab.get()) {
							CCItems.ITEMS.getDeferredRegister().getEntries().forEach(entry -> output.accept(entry.get()));
						}
					})).build());

	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> COPPER = CREATIVE_TABS.register("copper", () ->
			CreativeModeTab.builder()
					.title(Component.translatable("itemGroup.caverns_and_chasms.copper"))
					.icon(() -> new ItemStack(CCItems.WAXED_COPPER_INGOT.get()))
					.displayItems(((parameters, output) -> {
						if (CCConfig.COMMON.copperCreativeTab.get()) {
							addToTab(output,
									() -> Items.COPPER_INGOT, CCItems.EXPOSED_COPPER_INGOT, CCItems.WEATHERED_COPPER_INGOT, CCItems.OXIDIZED_COPPER_INGOT, CCItems.WAXED_COPPER_INGOT, CCItems.WAXED_EXPOSED_COPPER_INGOT, CCItems.WAXED_WEATHERED_COPPER_INGOT, CCItems.WAXED_OXIDIZED_COPPER_INGOT, () -> Items.BARRIER,
									COPPER_SWORD, EXPOSED_COPPER_SWORD, WEATHERED_COPPER_SWORD, OXIDIZED_COPPER_SWORD, WAXED_COPPER_SWORD, WAXED_EXPOSED_COPPER_SWORD, WAXED_WEATHERED_COPPER_SWORD, WAXED_OXIDIZED_COPPER_SWORD, () -> Items.BARRIER,
									COPPER_SHOVEL, EXPOSED_COPPER_SHOVEL, WEATHERED_COPPER_SHOVEL, OXIDIZED_COPPER_SHOVEL, WAXED_COPPER_SHOVEL, WAXED_EXPOSED_COPPER_SHOVEL, WAXED_WEATHERED_COPPER_SHOVEL, WAXED_OXIDIZED_COPPER_SHOVEL, () -> Items.BARRIER,
									COPPER_PICKAXE, EXPOSED_COPPER_PICKAXE, WEATHERED_COPPER_PICKAXE, OXIDIZED_COPPER_PICKAXE, WAXED_COPPER_PICKAXE, WAXED_EXPOSED_COPPER_PICKAXE, WAXED_WEATHERED_COPPER_PICKAXE, WAXED_OXIDIZED_COPPER_PICKAXE, () -> Items.BARRIER,
									COPPER_AXE, EXPOSED_COPPER_AXE, WEATHERED_COPPER_AXE, OXIDIZED_COPPER_AXE, WAXED_COPPER_AXE, WAXED_EXPOSED_COPPER_AXE, WAXED_WEATHERED_COPPER_AXE, WAXED_OXIDIZED_COPPER_AXE, () -> Items.BARRIER,
									COPPER_HOE, EXPOSED_COPPER_HOE, WEATHERED_COPPER_HOE, OXIDIZED_COPPER_HOE, WAXED_COPPER_HOE, WAXED_EXPOSED_COPPER_HOE, WAXED_WEATHERED_COPPER_HOE, WAXED_OXIDIZED_COPPER_HOE, () -> Items.BARRIER,
									COPPER_HELMET, EXPOSED_COPPER_HELMET, WEATHERED_COPPER_HELMET, OXIDIZED_COPPER_HELMET, WAXED_COPPER_HELMET, WAXED_EXPOSED_COPPER_HELMET, WAXED_WEATHERED_COPPER_HELMET, WAXED_OXIDIZED_COPPER_HELMET, () -> Items.BARRIER,
									COPPER_CHESTPLATE, EXPOSED_COPPER_CHESTPLATE, WEATHERED_COPPER_CHESTPLATE, OXIDIZED_COPPER_CHESTPLATE, WAXED_COPPER_CHESTPLATE, WAXED_EXPOSED_COPPER_CHESTPLATE, WAXED_WEATHERED_COPPER_CHESTPLATE, WAXED_OXIDIZED_COPPER_CHESTPLATE, () -> Items.BARRIER,
									COPPER_LEGGINGS, EXPOSED_COPPER_LEGGINGS, WEATHERED_COPPER_LEGGINGS, OXIDIZED_COPPER_LEGGINGS, WAXED_COPPER_LEGGINGS, WAXED_EXPOSED_COPPER_LEGGINGS, WAXED_WEATHERED_COPPER_LEGGINGS, WAXED_OXIDIZED_COPPER_LEGGINGS, () -> Items.BARRIER,
									COPPER_BOOTS, EXPOSED_COPPER_BOOTS, WEATHERED_COPPER_BOOTS, OXIDIZED_COPPER_BOOTS, WAXED_COPPER_BOOTS, WAXED_EXPOSED_COPPER_BOOTS, WAXED_WEATHERED_COPPER_BOOTS, WAXED_OXIDIZED_COPPER_BOOTS, () -> Items.BARRIER,
									COPPER_HORSE_ARMOR, EXPOSED_COPPER_HORSE_ARMOR, WEATHERED_COPPER_HORSE_ARMOR, OXIDIZED_COPPER_HORSE_ARMOR, WAXED_COPPER_HORSE_ARMOR, WAXED_EXPOSED_COPPER_HORSE_ARMOR, WAXED_WEATHERED_COPPER_HORSE_ARMOR, WAXED_OXIDIZED_COPPER_HORSE_ARMOR, () -> Items.BARRIER,
									() -> Blocks.COPPER_BLOCK, () -> Blocks.EXPOSED_COPPER, () -> Blocks.WEATHERED_COPPER, () -> Blocks.OXIDIZED_COPPER, () -> Blocks.WAXED_COPPER_BLOCK, () -> Blocks.WAXED_EXPOSED_COPPER, () -> Blocks.WAXED_WEATHERED_COPPER, () -> Blocks.WAXED_OXIDIZED_COPPER, () -> Items.BARRIER,
									() -> Blocks.CHISELED_COPPER, () -> Blocks.EXPOSED_CHISELED_COPPER, () -> Blocks.WEATHERED_CHISELED_COPPER, () -> Blocks.OXIDIZED_CHISELED_COPPER, () -> Blocks.WAXED_CHISELED_COPPER, () -> Blocks.WAXED_EXPOSED_CHISELED_COPPER, () -> Blocks.WAXED_WEATHERED_CHISELED_COPPER, () -> Blocks.WAXED_OXIDIZED_CHISELED_COPPER, () -> Items.BARRIER,
									() -> Blocks.COPPER_GRATE, () -> Blocks.EXPOSED_COPPER_GRATE, () -> Blocks.WEATHERED_COPPER_GRATE, () -> Blocks.OXIDIZED_COPPER_GRATE, () -> Blocks.WAXED_COPPER_GRATE, () -> Blocks.WAXED_EXPOSED_COPPER_GRATE, () -> Blocks.WAXED_WEATHERED_COPPER_GRATE, () -> Blocks.WAXED_OXIDIZED_COPPER_GRATE, () -> Items.BARRIER,
									() -> Blocks.CUT_COPPER, () -> Blocks.EXPOSED_CUT_COPPER, () -> Blocks.WEATHERED_CUT_COPPER, () -> Blocks.OXIDIZED_CUT_COPPER, () -> Blocks.WAXED_CUT_COPPER, () -> Blocks.WAXED_EXPOSED_CUT_COPPER, () -> Blocks.WAXED_WEATHERED_CUT_COPPER, () -> Blocks.WAXED_OXIDIZED_CUT_COPPER, () -> Items.BARRIER,
									() -> Blocks.CUT_COPPER_SLAB, () -> Blocks.EXPOSED_CUT_COPPER_SLAB, () -> Blocks.WEATHERED_CUT_COPPER_SLAB, () -> Blocks.OXIDIZED_CUT_COPPER_SLAB, () -> Blocks.WAXED_CUT_COPPER_SLAB, () -> Blocks.WAXED_EXPOSED_CUT_COPPER_SLAB, () -> Blocks.WAXED_WEATHERED_CUT_COPPER_SLAB, () -> Blocks.WAXED_OXIDIZED_CUT_COPPER_SLAB, () -> Items.BARRIER,
									() -> Blocks.CUT_COPPER_STAIRS, () -> Blocks.EXPOSED_CUT_COPPER_STAIRS, () -> Blocks.WEATHERED_CUT_COPPER_STAIRS, () -> Blocks.OXIDIZED_CUT_COPPER_STAIRS, () -> Blocks.WAXED_CUT_COPPER_STAIRS, () -> Blocks.WAXED_EXPOSED_CUT_COPPER_STAIRS, () -> Blocks.WAXED_WEATHERED_CUT_COPPER_STAIRS, () -> Blocks.WAXED_OXIDIZED_CUT_COPPER_STAIRS, () -> Items.BARRIER,
									COPPER_BRICKS, EXPOSED_COPPER_BRICKS, WEATHERED_COPPER_BRICKS, OXIDIZED_COPPER_BRICKS, WAXED_COPPER_BRICKS, WAXED_EXPOSED_COPPER_BRICKS, WAXED_WEATHERED_COPPER_BRICKS, WAXED_OXIDIZED_COPPER_BRICKS, () -> Items.BARRIER,
									COPPER_BRICK_STAIRS, EXPOSED_COPPER_BRICK_STAIRS, WEATHERED_COPPER_BRICK_STAIRS, OXIDIZED_COPPER_BRICK_STAIRS, WAXED_COPPER_BRICK_STAIRS, WAXED_EXPOSED_COPPER_BRICK_STAIRS, WAXED_WEATHERED_COPPER_BRICK_STAIRS, WAXED_OXIDIZED_COPPER_BRICK_STAIRS, () -> Items.BARRIER,
									COPPER_BRICK_SLAB, EXPOSED_COPPER_BRICK_SLAB, WEATHERED_COPPER_BRICK_SLAB, OXIDIZED_COPPER_BRICK_SLAB, WAXED_COPPER_BRICK_SLAB, WAXED_EXPOSED_COPPER_BRICK_SLAB, WAXED_WEATHERED_COPPER_BRICK_SLAB, WAXED_OXIDIZED_COPPER_BRICK_SLAB, () -> Items.BARRIER,
									COPPER_BRICK_WALL, EXPOSED_COPPER_BRICK_WALL, WEATHERED_COPPER_BRICK_WALL, OXIDIZED_COPPER_BRICK_WALL, WAXED_COPPER_BRICK_WALL, WAXED_EXPOSED_COPPER_BRICK_WALL, WAXED_WEATHERED_COPPER_BRICK_WALL, WAXED_OXIDIZED_COPPER_BRICK_WALL, () -> Items.BARRIER,
									CHISELED_COPPER_BRICKS, EXPOSED_CHISELED_COPPER_BRICKS, WEATHERED_CHISELED_COPPER_BRICKS, OXIDIZED_CHISELED_COPPER_BRICKS, WAXED_CHISELED_COPPER_BRICKS, WAXED_EXPOSED_CHISELED_COPPER_BRICKS, WAXED_WEATHERED_CHISELED_COPPER_BRICKS, WAXED_OXIDIZED_CHISELED_COPPER_BRICKS, () -> Items.BARRIER,
									() -> Blocks.COPPER_DOOR, () -> Blocks.EXPOSED_COPPER_DOOR, () -> Blocks.WEATHERED_COPPER_DOOR, () -> Blocks.OXIDIZED_COPPER_DOOR, () -> Blocks.WAXED_COPPER_DOOR, () -> Blocks.WAXED_EXPOSED_COPPER_DOOR, () -> Blocks.WAXED_WEATHERED_COPPER_DOOR, () -> Blocks.WAXED_OXIDIZED_COPPER_DOOR, () -> Items.BARRIER,
									() -> Blocks.COPPER_TRAPDOOR, () -> Blocks.EXPOSED_COPPER_TRAPDOOR, () -> Blocks.WEATHERED_COPPER_TRAPDOOR, () -> Blocks.OXIDIZED_COPPER_TRAPDOOR, () -> Blocks.WAXED_COPPER_TRAPDOOR, () -> Blocks.WAXED_EXPOSED_COPPER_TRAPDOOR, () -> Blocks.WAXED_WEATHERED_COPPER_TRAPDOOR, () -> Blocks.WAXED_OXIDIZED_COPPER_TRAPDOOR, () -> Items.BARRIER,
									LIFT_BUTTON, EXPOSED_LIFT_BUTTON, WEATHERED_LIFT_BUTTON, OXIDIZED_LIFT_BUTTON, WAXED_LIFT_BUTTON, WAXED_EXPOSED_LIFT_BUTTON, WAXED_WEATHERED_LIFT_BUTTON, WAXED_OXIDIZED_LIFT_BUTTON, () -> Items.BARRIER,
									() -> Blocks.LIGHTNING_ROD, EXPOSED_LIGHTNING_ROD, WEATHERED_LIGHTNING_ROD, OXIDIZED_LIGHTNING_ROD, WAXED_LIGHTNING_ROD, WAXED_EXPOSED_LIGHTNING_ROD, WAXED_WEATHERED_LIGHTNING_ROD, WAXED_OXIDIZED_LIGHTNING_ROD, () -> Items.BARRIER,
									COPPER_BARS, EXPOSED_COPPER_BARS, WEATHERED_COPPER_BARS, OXIDIZED_COPPER_BARS, WAXED_COPPER_BARS, WAXED_EXPOSED_COPPER_BARS, WAXED_WEATHERED_COPPER_BARS, WAXED_OXIDIZED_COPPER_BARS, () -> Items.BARRIER,
									COPPER_CHAIN, EXPOSED_COPPER_CHAIN, WEATHERED_COPPER_CHAIN, OXIDIZED_COPPER_CHAIN, WAXED_COPPER_CHAIN, WAXED_EXPOSED_COPPER_CHAIN, WAXED_WEATHERED_COPPER_CHAIN, WAXED_OXIDIZED_COPPER_CHAIN, () -> Items.BARRIER,
									COPPER_LANTERN, EXPOSED_COPPER_LANTERN, WEATHERED_COPPER_LANTERN, OXIDIZED_COPPER_LANTERN, WAXED_COPPER_LANTERN, WAXED_EXPOSED_COPPER_LANTERN, WAXED_WEATHERED_COPPER_LANTERN, WAXED_OXIDIZED_COPPER_LANTERN, () -> Items.BARRIER,
									FLOODLIGHT, EXPOSED_FLOODLIGHT, WEATHERED_FLOODLIGHT, OXIDIZED_FLOODLIGHT, WAXED_FLOODLIGHT, WAXED_EXPOSED_FLOODLIGHT, WAXED_WEATHERED_FLOODLIGHT, WAXED_OXIDIZED_FLOODLIGHT, () -> Items.BARRIER,
									() -> Blocks.COPPER_BULB, () -> Blocks.EXPOSED_COPPER_BULB, () -> Blocks.WEATHERED_COPPER_BULB, () -> Blocks.OXIDIZED_COPPER_BULB, () -> Blocks.WAXED_COPPER_BULB, () -> Blocks.WAXED_EXPOSED_COPPER_BULB, () -> Blocks.WAXED_WEATHERED_COPPER_BULB, () -> Blocks.WAXED_OXIDIZED_COPPER_BULB, () -> Items.BARRIER,
									TOOLBOX, EXPOSED_TOOLBOX, WEATHERED_TOOLBOX, OXIDIZED_TOOLBOX, WAXED_TOOLBOX, WAXED_EXPOSED_TOOLBOX, WAXED_WEATHERED_TOOLBOX, WAXED_OXIDIZED_TOOLBOX, () -> Items.BARRIER,
									COPPER_RAIL, EXPOSED_COPPER_RAIL, WEATHERED_COPPER_RAIL, OXIDIZED_COPPER_RAIL, WAXED_COPPER_RAIL, WAXED_EXPOSED_COPPER_RAIL, WAXED_WEATHERED_COPPER_RAIL, WAXED_OXIDIZED_COPPER_RAIL, () -> Items.BARRIER
							);
						}
					})).build());


	@SafeVarargs
	public static void addToTab(CreativeModeTab.Output output, Supplier<? extends ItemLike>... items) {
		int count = 0;
		for (Supplier<? extends ItemLike> supplier : items) {
			ItemLike item = supplier.get();
			if (item == Items.BARRIER) {
				ItemStack barrier = new ItemStack(item);
				barrier.set(DataComponents.CUSTOM_NAME, Component.literal(String.valueOf(count++)));
				output.accept(barrier);
			} else {
				output.accept(new ItemStack(item.asItem()));
			}
		}
	}

	@SubscribeEvent
	public static void onModifyComponents(BuildCreativeModeTabContentsEvent event) {
	}
}